name: Install with pip

on:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install
        run: pip install -r requirements.txt

      # Zip the cache into a single file.
      - name: Zip
        run: tar -czf cache-pip.tar.gz ~/.cache/pip

      - uses: actions/upload-artifact@v3
        with:
          name: cache-pip
          path: cache-pip.tar.gz
